import "./globals.css";
import type { Metadata } from "next";
import { Saira_Condensed, Saira_Extra_Condensed } from "next/font/google";
import { Roboto } from "next/font/google";
import { Noto_Sans_Old_Sogdian } from "next/font/google";
import { DM_Sans } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/Footer";

const sairaExtraCondensed = Saira_Extra_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-saira-extra-condensed",
});

const sairaCondensed = Saira_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-saira-condensed",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-roboto",
});

const notoSansOldSogdian = Noto_Sans_Old_Sogdian({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-noto-sans-old-sogdian",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${sairaExtraCondensed.variable} ${roboto.variable} ${notoSansOldSogdian.variable} ${sairaCondensed.variable} ${dmSans.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
